[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "odyssey"
version = "0.0.1"
description = "Embarking on a quest to conquer NetHack with Reinforcement Learning."
authors = [
  { name = "Dominik Jeurissen" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
dependencies = [
    # Setup / Dev
    "pytest",
    "python-dotenv",
    "ruff",
    "cookiecutter-data-science",

    # Utils
    "loguru",
    "typer",
    "numpy",
    "pandas",
    "ipykernel",
    "tqdm",
    "matplotlib",
    "rich",
    "hydra-core",
    "opencv-python",

    # OpenAI Gym / NLE
    "nle",
    "gymnasium<1.0.0",

    # Machine Learning
    "torch",
    "torchvision",
    "lightning",
    "torchrl",
    "av",  # for video recording
    "sentence-transformers==3.0.0",
    "h5py",
    "wandb",
    "captum"
]

requires-python = "~=3.10.0"


[tool.ruff]
line-length = 99
src = ["odyssey"]
include = ["pyproject.toml", "odyssey/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["odyssey"]
force-sort-within-sections = true

