char_embedding_dim: 16
obs_embedding_dim: 128
context_embedding_dim: 256
context_length: 100
future_length: 30
batch_size: 32
samples_per_trajectory: 16
train_data_path: /workspace/data/nld_nao_train.h5
test_data_path: /workspace/data/nld_nao_test.h5
max_epochs: 10
steps_per_epoch: 500
evaluation_steps: 50