from nle.nethack import (
    # See nle/include/nleobs.h for the original definitions
    NLE_BL_HUNGER as BLSTATS_HUNGER_INDEX,
    NLE_BL_CONDITION as BLSTATS_CONDITION_INDEX,
    NLE_BL_HP as BLSTATS_HP_INDEX,
    NLE_BL_HPMAX as BLSTATS_HPMAX_INDEX,
    NLE_BL_ENE as BLSTATS_ENERGY_INDEX,
    NLE_BL_ENEMAX as BLSTATS_ENERGYMAX_INDEX,
    NLE_BL_STR25 as BLSTATS_STRENGTH_INDEX,
    NLE_BL_STR125 as BLSTATS_STRENGTH_PERCENTAGE_INDEX,
    NLE_BL_DEX as BLSTATS_DEXTERITY_INDEX,
    NLE_BL_CON as BLSTATS_CONSTITUTION_INDEX,
    NLE_BL_INT as BLSTATS_INTELLIGENCE_INDEX,
    NLE_BL_WIS as BLSTATS_WISDOM_INDEX,
    NLE_BL_CHA as BLSTATS_CHARISMA_INDEX,
    NLE_BL_AC as BLSTATS_ARMOR_CLASS_INDEX,
    NLE_BL_CAP as BLSTATS_CARRYING_CAPACITY_INDEX,
    NLE_BL_X as BLSTATS_X_INDEX,
    NLE_BL_Y as BLSTATS_Y_INDEX,
    NLE_BL_SCORE as BLSTATS_SCORE_INDEX,
    NLE_BL_GOLD as BLSTATS_GOLD_INDEX,
    NLE_BL_XP as BLSTATS_EXPERIENCE_LEVEL_INDEX,
    NLE_BL_EXP as BLSTATS_EXPERIENCE_POINTS_INDEX,
    NLE_BL_TIME as BLSTATS_TIME_INDEX,
    NLE_BL_DNUM as BLSTATS_DUNGEON_NUMBER_INDEX,
    NLE_BL_DLEVEL as BLSTATS_LEVEL_NUMBER_INDEX,
    NLE_BL_DEPTH as BLSTATS_DEPTH_INDEX,
    NLE_BL_HD as BLSTATS_MONSTER_LEVEL_INDEX,
    NLE_BL_ALIGN as BLSTATS_ALIGNMENT_INDEX,
)

MAP_HEIGHT = 21
MAP_WIDTH = 79